### ISSUE TITLE
Error disabling if CiviRules is installed after fastactionlinks

### ISSUE THREAD

**Issue by twomice** [PalanteJon/org.takethestreets.fastactionlinks#2]
(This error is observed with commit f50420e9cf644dfafc9641aacbfdee05cce629e4, i.e., after the fix of #1.)

To reproduce:

1. Use CiviCRM 4.7.18, where CiviRules is not installed.
2. Install fastactionlinks. Observe it installs with no problem.
3. Install CiviRules extension.
4. Disable fastactionlinks. Note that extension is indeed disabled, but observe fatal error "API error: Either class_name or a combination of object_name and op is mandatory".
5. Uninstall fastactionlinks. Observe no errors.

**Comment by MegaphoneJon** [comment]
This is actually a bug in CiviRules.  I had done so much work on this leading up to CiviCon that I forgot that I'd actually filed a [bug report](https://github.com/CiviCooP/org.civicoop.civirules/issues/149) and a [PR](https://github.com/CiviCooP/org.civicoop.civirules/issues/150) to fix this on CiviRules!

Unfortunately, a new CiviRules release hasn't been tagged since May, so this will still affect people installing today - but the error doesn't affect intended functionality, and has been fixed upstream, so I'm going to close it here.
