### ISSUE TITLE
Two issues since upgrading

### ISSUE THREAD

**Issue by edward-peters** [PalanteJon/org.takethestreets.fastactionlinks#7]
Thank you for this brilliant extension. Since recently upgrading to the latest release two things have changed:

1. Before, when clicking a link, the whole row disappeared (i.e. not just being dimmed), but now it does not disappear and is only dimmed. Is this a change of behaviour or am I missing something?
2. If I choose as the Action to trigger a CiviRules rule, in the autocomplete of rules there are several results but all say 'null' not the name of the rule. Anything I can do about that?

Thanks for your help.

**Comment by MegaphoneJon** [comment]
Thank you @edward-peters.  What version did you upgrade from, and to?  And can you paste a screenshot of the second issue?

**Comment by edward-peters** [comment]
@MegaphoneJon Good of you to respond!
The upgrade was from 2.0 to 2.0.2
Attached is a screenshot. I have several FALs each triggering a rule, which is why multiple instances of 'null' are showing. They still work so the correct rule must still be selected.
Thank you so much for your help
<img width="581" alt="Screenshot 2022-01-10 at 10 33 39" src="https://user-images.githubusercontent.com/43352605/148744441-d730e667-6e30-4faa-b387-555d149a0771.png">
.

**Comment by edward-peters** [comment]
@MegaphoneJon Would you have time to update me on this please?

**Comment by MegaphoneJon** [comment]
Hi Edward,

The first issue - dimming on use instead of disappearing - is the intended behavior.  I'm not sure what was happening before, but that was the bug, this is correct.

The second issue is a problem with CiviRules - I took a quick look and don't have time to troubleshoot further, but they don't define a labelField in the XML that defines their data structure.  I believe older versions of Civi, where data structure was less consistent, worked around this with some "magic" to guess the label field, but now it must be defined explicitly.  You'll have to open a ticket with them.  To replicate this issue, go to API Explorer and do the `getlist` action with nothing else defined for the CiviRuleRule entity, and compare that to, say, `getlist` for Contact or ContributionPage entity to see what I mean.

**Comment by edward-peters** [comment]
Hi Jon,
Many thanks for these explanations. I will open a ticket with CiviRules.
Thanks again for our very valuable Extension.
Edward
